# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exibe.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65xibe.proto\x12\x05\x65xibe\"+\n\x0c\x45xibeRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0e\n\x06origem\x18\x02 \x01(\t\"!\n\rExibeResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2n\n\x05\x45xibe\x12\x34\n\x05\x65xibe\x12\x13.exibe.ExibeRequest\x1a\x14.exibe.ExibeResponse\"\x00\x12/\n\x07termina\x12\x0c.exibe.Empty\x1a\x14.exibe.ExibeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exibe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXIBEREQUEST']._serialized_start=22
  _globals['_EXIBEREQUEST']._serialized_end=65
  _globals['_EXIBERESPONSE']._serialized_start=67
  _globals['_EXIBERESPONSE']._serialized_end=100
  _globals['_EMPTY']._serialized_start=102
  _globals['_EMPTY']._serialized_end=109
  _globals['_EXIBE']._serialized_start=111
  _globals['_EXIBE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
