# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exibe.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65xibe.proto\x12\x05\x65xibe\"-\n\x08mensagem\x12\x11\n\tsmensagem\x18\x01 \x01(\t\x12\x0e\n\x06origem\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2Z\n\x05\x65xibe\x12(\n\x05\x65xibe\x12\x0f.exibe.mensagem\x1a\x0c.exibe.Empty\"\x00\x12\'\n\x07termina\x12\x0c.exibe.Empty\x1a\x0c.exibe.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exibe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MENSAGEM']._serialized_start=22
  _globals['_MENSAGEM']._serialized_end=67
  _globals['_EMPTY']._serialized_start=69
  _globals['_EMPTY']._serialized_end=76
  _globals['_EXIBE']._serialized_start=78
  _globals['_EXIBE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
