# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import exibe_pb2 as exibe__pb2


class ExibeStub(object):
    """Definição do serviço para o servidor de exibição
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.exibe = channel.unary_unary(
                '/exibe.Exibe/exibe',
                request_serializer=exibe__pb2.ExibeRequest.SerializeToString,
                response_deserializer=exibe__pb2.ExibeResponse.FromString,
                )
        self.termina = channel.unary_unary(
                '/exibe.Exibe/termina',
                request_serializer=exibe__pb2.Empty.SerializeToString,
                response_deserializer=exibe__pb2.ExibeResponse.FromString,
                )


class ExibeServicer(object):
    """Definição do serviço para o servidor de exibição
    """

    def exibe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def termina(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExibeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'exibe': grpc.unary_unary_rpc_method_handler(
                    servicer.exibe,
                    request_deserializer=exibe__pb2.ExibeRequest.FromString,
                    response_serializer=exibe__pb2.ExibeResponse.SerializeToString,
            ),
            'termina': grpc.unary_unary_rpc_method_handler(
                    servicer.termina,
                    request_deserializer=exibe__pb2.Empty.FromString,
                    response_serializer=exibe__pb2.ExibeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exibe.Exibe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Exibe(object):
    """Definição do serviço para o servidor de exibição
    """

    @staticmethod
    def exibe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exibe.Exibe/exibe',
            exibe__pb2.ExibeRequest.SerializeToString,
            exibe__pb2.ExibeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def termina(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exibe.Exibe/termina',
            exibe__pb2.Empty.SerializeToString,
            exibe__pb2.ExibeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
